#!/bin/bash

#command to create dynamodb table
function createDynamodb() {
   aws dynamodb create-table \
    --table-name terraform-lock-playground \
    --attribute-definitions 'AttributeName=LockID,AttributeType=S' \
    --key-schema 'AttributeName=LockID,KeyType=HASH' \
    --provisioned-throughput 'ReadCapacityUnits=1,WriteCapacityUnits=1' \
    --profile vonage-rbac-webapp-be-playground \
    --region us-east-1
}
#command to create s3 bucket
function createBucket() {
    aws s3api create-bucket \
    --bucket tf-state-webapp-be-playground \
    --profile vonage-rbac-webapp-be-playground \
    --region us-east-1
   }
echo "Creating AWS S3 bucket"
createBucket   # Calling the createbucket function  
echo "Creating Dynamodb table"
createDynamodb # calling our createdynamodb function
